// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXuaO1dmCqlDWSD4t5KI1IK9G25q2nNSc',
    appId: '1:1082962223047:web:30e165f9bc0caa420183e2',
    messagingSenderId: '1082962223047',
    projectId: 'noteapp-ee9cc',
    authDomain: 'noteapp-ee9cc.firebaseapp.com',
    storageBucket: 'noteapp-ee9cc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd9wqx5FjGqrKCTj6yI94w6MBtcrwprWY',
    appId: '1:1082962223047:android:7669c01a97ac5c230183e2',
    messagingSenderId: '1082962223047',
    projectId: 'noteapp-ee9cc',
    storageBucket: 'noteapp-ee9cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkDYpw4okRY5NgwqFSdZI6x1AmeUn_TbE',
    appId: '1:1082962223047:ios:32f0646f40f849cc0183e2',
    messagingSenderId: '1082962223047',
    projectId: 'noteapp-ee9cc',
    storageBucket: 'noteapp-ee9cc.appspot.com',
    iosClientId: '1082962223047-1p3frbvprfl2tncnfjmh8fdudk011930.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkDYpw4okRY5NgwqFSdZI6x1AmeUn_TbE',
    appId: '1:1082962223047:ios:32f0646f40f849cc0183e2',
    messagingSenderId: '1082962223047',
    projectId: 'noteapp-ee9cc',
    storageBucket: 'noteapp-ee9cc.appspot.com',
    iosClientId: '1082962223047-1p3frbvprfl2tncnfjmh8fdudk011930.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteapp',
  );
}
